servers:
  - type: udp
    args:
      listen: 0.0.0.0:5353

upstreams:
  - address: 223.5.5.5:53
  - address: 223.6.6.6:53
  - address: 8.8.8.8:53
  - address: 8.8.4.4:53
  - address: 1.1.1.1:53
  - address: 1.0.0.1:53
